fields:
  form_section:
    type: section
    display: Form Settings
  captcha_service:
    type: select
    options:
      Recaptcha: reCAPTCHA
      Hcaptcha: hCaptcha
  forms:
    type: suggest
    mode: form
    instructions: Select the forms where Captcha will be used.
  user_registration:
    type: toggle
    instructions: Toggle to use Captcha in User Registration form.
  error_message:
    type: text
    instructions: The message that will be returned if validation fails.
  site_key:
    type: text
    display: API Site Key
    width: 50
  secret:
    type: text
    display: API Secret
    width: 50
  extra_settings_section:
    type: section
    display: Extra Settings (reCAPTCHA-only)
    show_when:
      captcha_service: Recaptcha
  invisible:
    type: toggle
    width: 50
    show_when:
      captcha_service: Recaptcha
  hide_badge:
    display: Hide reCAPTCHA Badge
    type: toggle
    width: 50
    show_when:
      captcha_service: Recaptcha
      invisible: true
  disclaimer:
    display: Disclaimer Message
    type: markdown
    show_when:
      captcha_service: Recaptcha
      hide_badge: true
  multi_keys:
    type: toggle
    display: Use Multiple Keys?
    show_when:
      captcha_service: Recaptcha
  site_keys:
    type: grid
    show_when:
      captcha_service: Recaptcha
      multi_keys: true
    fields:
      domains:
        type: textarea
        width: 33
      site_key:
        type: text
        display: Site Key
        width: 33
      secret:
        type: text
        width: 33
      invisible:
        type: toggle
        width: 33
